name: CI Fullstack Pipeline

# Déclencheurs : Quand est-ce que la pipeline s'exécute ?
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # --- JOB BACKEND ---
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'

      - name: Installation des dépendances
        run: npm ci

      - name: Vérification du Lint (Qualité)
        run: npm run lint || echo "Ajoute un script lint dans ton package.json !"

      - name: Build du projet
        run: echo "Le backend Node n'a pas toujours besoin de build, mais on peut tester ici."

  # --- JOB FRONTEND ---
  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Installation des dépendances
        run: npm ci

      - name: Build de l'application React
        run: npm run build